Repository srm-kzilla/zeus-backend, pull requests merged in 2022-10, with the labels that each got.

#49 :lipstick: Update reg email template
  templates/newUserTemplate.html
Labels: good first issue

#52 add epoch
  api/users/controller/user-controller.go
  api/users/model/users-model.go
Labels: hacktoberfest

#53 fix format
  api/users/controller/user-controller.go
Labels: hacktoberfest, hacktoberfest-accepted
